# Generated by Django 4.1.7 on 2023-05-14 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.UUID('cb238130-0f8d-415a-8e51-b115a28be830'))),
                ('bio', models.CharField(max_length=350, null=True)),
                ('profile_image', models.ImageField(default='', upload_to='user-image')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('dtime', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
