# Generated by Django 4.1.7 on 2023-05-14 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profile_image_alter_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('4e95396e-413d-4dfb-857d-91a3423aa74d')),
        ),
    ]
